[package]
name = "me3-mod-protocol"
edition = "2021"
version.workspace = true
repository.workspace = true
license.workspace = true
description = "Schema definition for me3 mod profiles"

[dependencies]
schemars.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_yaml.workspace = true
toml.workspace = true
thiserror.workspace = true
topological-sort = "0.2.2"

[dev-dependencies]
expect-test.workspace = true

[lints]
workspace = true
